# Generated by Django 4.2.14 on 2024-10-11 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0010_choicesleavetype_staff_leave'),
        ('setup', '0004_department_sch_fac_alter_bankbranch_bank_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitlement', models.IntegerField()),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.academicyear')),
                ('staff_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.staffcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_entitlement', models.IntegerField()),
                ('staff_rank', models.CharField(max_length=25)),
                ('fin_year', models.CharField(default='2025/26', max_length=10)),
                ('leave_description', models.CharField(max_length=250)),
                ('leave_approved_by', models.CharField(blank=True, default='0000', max_length=250, null=True)),
                ('days_taken', models.IntegerField()),
                ('leave_arrears', models.IntegerField()),
                ('leave_approved_on', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('leave_start_date', models.DateField(blank=True, null=True)),
                ('leave_end_date', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
