# Generated by Django 4.2.13 on 2024-06-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_entitlement', models.IntegerField()),
                ('staff_rank', models.CharField(max_length=25)),
                ('fin_year', models.CharField(default='2025/26', max_length=10)),
                ('leave_description', models.CharField(max_length=250)),
                ('leave_approved_by', models.CharField(blank=True, default='0000', max_length=250, null=True)),
                ('days_taken', models.IntegerField()),
                ('leave_arrears', models.IntegerField()),
                ('leave_approved_on', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('leave_start_date', models.DateField(blank=True, null=True)),
                ('leave_end_date', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
