# Generated by Django 5.0.3 on 2024-05-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0014_alter_kith_kith_relationship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_entitlement', models.IntegerField()),
                ('fin_year', models.CharField(default='2025/26', max_length=10)),
                ('leave_description', models.CharField(max_length=250)),
                ('leave_approved_by', models.CharField(blank=True, default='0000', max_length=250, null=True)),
                ('days_taken', models.IntegerField()),
                ('leave_arrears', models.IntegerField()),
                ('leave_approved_on', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
