# Generated by Django 5.0.3 on 2024-05-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='staff_rank',
            field=models.CharField(default='SM', max_length=25),
            preserve_default=False,
        ),
    ]
