# Generated by Django 4.2.14 on 2024-10-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='academic_year',
            field=models.CharField(max_length=10), 
        ),
    ]
