# Generated by Django 5.0.3 on 2024-05-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_staff_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_approved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
