# Generated by Django 4.2.14 on 2025-01-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_academicyear_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveentitlement',
            name='staff_cat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Category'),
        ),
    ]
