# Generated by Django 4.2.14 on 2025-01-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_alter_medicalentitlement_academic_year_and_more'),
        ('leave', '0003_alter_leaveentitlement_staff_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveentitlement',
            name='academic_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
