# Generated by Django 4.2.14 on 2025-10-23 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, EUR, GHS)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Currency name (e.g., US Dollar, Euro, Ghana Cedi)', max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, €, ₵)', max_length=10)),
                ('decimal_places', models.PositiveIntegerField(default=2, help_text='Number of decimal places')),
                ('is_active', models.BooleanField(default=True)),
                ('is_base_currency', models.BooleanField(default=False, help_text='Base currency for the organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='journalline',
            name='base_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credit amount in base currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='journalline',
            name='base_debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Debit amount in base currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='journalline',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Exchange rate to base currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='ledgerbalance',
            name='base_opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ledgerbalance',
            name='base_total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ledgerbalance',
            name='base_total_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Account currency', null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.currency'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Transaction currency', null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.currency'),
        ),
        migrations.AddField(
            model_name='ledgerbalance',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Balance currency', null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.currency'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate', max_digits=12)),
                ('effective_date', models.DateField(help_text='Date when this rate becomes effective')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_rates', to='ledger.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_rates', to='ledger.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-effective_date'],
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
    ]
