# Generated by Django 4.2.14 on 2025-10-23 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_currency_journalline_base_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashvoucher',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Voucher currency', null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.currency'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='purpose',
            field=models.CharField(blank=True, help_text='Business purpose', max_length=255),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Receipt number if available', max_length=50),
        ),
    ]
