# Generated by Django 4.2.14 on 2025-11-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_budget_budgetline'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Cost center (Department/Directorate)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journallines', to='ledger.account'),
        ),
    ]
