# Generated by Django 4.2.14 on 2025-11-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_journal_cost_center_alter_journalline_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True, help_text='Transaction description (optional)', null=True),
        ),
    ]
