# Generated by Django 4.2.14 on 2025-11-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_journal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='cost_center',
        ),
        migrations.AddField(
            model_name='journalline',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Cost center (Department/Directorate)', max_length=200, null=True),
        ),
    ]
