# Generated by Django 4.2.14 on 2025-11-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_remove_journal_cost_center_journalline_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='date',
            field=models.DateField(blank=True, help_text='Line transaction date', null=True),
        ),
    ]
