# Generated by Django 4.2.14 on 2025-01-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_cat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Category')),
                ('entitlement', models.IntegerField()),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
