# Generated by Django 4.2.14 on 2025-07-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalentitlement',
            name='treatment_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Treatment Type'),
        ),
        migrations.AlterField(
            model_name='medicalentitlement',
            name='entitlement',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
