# Generated by Django 4.2.14 on 2025-01-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalentitlement',
            name='academic_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalentitlement',
            name='staff_cat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Category'),
        ),
    ]
