# Generated by Django 5.0.3 on 2024-03-18 16:18

import django.db.models.deletion
import setup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('staffno', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Staff Number')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Rev. Dr.', 'Rev. Dr.'), ('Rev.', 'Rev.'), ('Ms.', 'Ms.'), ('Miss.', 'Miss.'), ('Rev. Prof.', 'Rev. Prof.'), ('Rev. Mrs.', 'Rev. Mrs.'), ('Bro.', 'Bro.'), ('Sis.', 'Sis.'), ('Fr.', 'Fr.'), ('Rev Fr.', 'Rev Fr.'), ('Rev. Sis.', 'Rev. Sis.')], max_length=20, verbose_name='Title of Courtesy')),
                ('lname', models.CharField(max_length=120, verbose_name='Surname')),
                ('fname', models.CharField(max_length=120, verbose_name='First Name')),
                ('middlenames', models.CharField(blank=True, max_length=120, null=True, verbose_name='Middle Names')),
                ('suffix', models.CharField(blank=True, choices=[('Jr', 'Jr'), ('Jnr', 'Jnr'), ('Snr', 'Snr'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], max_length=20, null=True, verbose_name='Name Suffixe')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')])),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('ssnitno', models.CharField(blank=True, max_length=50, null=True, verbose_name='SSNIT No.')),
                ('gcardno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ghana Card No.')),
                ('heq', models.CharField(blank=True, choices=[('None', 'None'), ('BECE', 'BECE'), ('WASSCE', 'WASSCE'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('First Degree', 'First Degree'), ('MPhil', 'MPhil'), ('MSc', 'MSc'), ('MBA', 'MBA'), ('MA', 'MA'), ('EMBA', 'EMBA'), ('PhD', 'PhD'), ('PGDip', 'PGDip')], max_length=100, null=True, verbose_name='Highest Academic Qualification')),
                ('hpq', models.CharField(blank=True, max_length=100, null=True, verbose_name='Highest Professional Qualification')),
                ('active_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Active Phone No.')),
                ('active_status', models.CharField(choices=[('Active', 'Active'), ('Retired', 'Retired'), ('Suspended', 'Suspended'), ('Dismissed', 'Dismissed'), ('Interdicted', 'Interdicted'), ('Sabbatical', 'Sabbatical'), ('Inactive', 'Inactive')], default='Active', max_length=15, verbose_name='Staff Status')),
                ('home_town', models.CharField(blank=True, max_length=100, null=True, verbose_name='Home Town')),
                ('region', models.CharField(blank=True, choices=[('GAR', 'Greater Accra'), ('WR', 'Western'), ('NR', 'Northern'), ('ER', 'Eastern'), ('VR', 'Volta'), ('OR', 'Oti'), ('UWR', 'Upper West'), ('UER', 'Upper East'), ('NER', 'North East'), ('BER', 'Bono East'), ('AS', 'Ashanti'), ('AR', 'Ahafo'), ('WNR', 'Western North'), ('CR', 'Central'), ('SR', 'Savannah'), ('BR', 'Bono')], max_length=50, null=True, verbose_name='Region')),
                ('rba', models.CharField(choices=[('MGT', 'Management'), ('HOD', 'Head of Dept/Directorate'), ('SUP', 'Unit/Section Head'), ('REG', 'Regular Staff')], default='REG', max_length=10, verbose_name='Role-Based Access')),
                ('doe', models.DateField(verbose_name='Date Employed')),
                ('staff_rank', models.CharField(blank=True, choices=[('Mgt', 'Management'), ('SM', 'Senior Member'), ('SS', 'Senior Staff'), ('JS', 'Junior Staff')], max_length=50, null=True, verbose_name='Staff Rank')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title')),
            ],
        ),
        migrations.CreateModel(
            name='Kith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kith_lname', models.CharField(max_length=120, verbose_name='Surname')),
                ('kith_fname', models.CharField(max_length=120, verbose_name='First Name')),
                ('kith_middlenames', models.CharField(blank=True, max_length=120, null=True, verbose_name='Middle Names')),
                ('kith_relationship', models.CharField(choices=[('Wife', 'Wife'), ('Husband', 'Husband'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Self', 'Self')])),
                ('kith_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')])),
                ('kith_dob', models.DateField(verbose_name='Date of Birth')),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attended', models.DateField()),
                ('complaint', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('Wife', 'Wife'), ('Husband', 'Husband'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Self', 'Self')])),
                ('treatment_cost', models.IntegerField()),
                ('quota_balance', models.IntegerField()),
                ('hospital_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.hospital')),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Postal_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='P.O.Box Number')),
                ('town', models.CharField(blank=True, max_length=50, null=True, verbose_name='Town')),
                ('care_of', models.CharField(blank=True, max_length=100, null=True, verbose_name='C/O')),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assoc_code', models.CharField(max_length=50, verbose_name=setup.models.ProfBody)),
                ('membershipno', models.CharField(max_length=20, verbose_name='Membership Number')),
                ('date_joined', models.DateField(verbose_name='Date Joined')),
                ('hra', models.CharField(default='Member', max_length=50, verbose_name='Highest Rank Attained')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Res_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='House Number')),
                ('street_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Street Name')),
                ('town', models.CharField(blank=True, max_length=50, null=True, verbose_name='Town')),
                ('landmark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nearest Landmark')),
                ('gps_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='GPS Address')),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_studied', models.CharField(blank=True, max_length=100, null=True, verbose_name='Program of Study')),
                ('start_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Start Date(mm/yyyy)')),
                ('finish_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Start Date(mm/yyyy)')),
                ('any_post', models.CharField(blank=True, max_length=50, null=True, verbose_name='Position Held')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('school_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.school')),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='StaffBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')])),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')])),
                ('account_date', models.DateField()),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.bankbranch')),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
