# Generated by Django 5.0.3 on 2024-03-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_pix',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
