# Generated by Django 4.2.14 on 2025-01-25 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalHistorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prev_staff_category', models.CharField(blank=True, max_length=120, null=True)),
                ('new_staff_category', models.CharField(blank=True, max_length=120, null=True)),
                ('prev_job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('new_job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('prev_position', models.CharField(blank=True, max_length=120, null=True)),
                ('new_position', models.CharField(blank=True, max_length=120, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_disapproved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_renewals', to=settings.AUTH_USER_MODEL)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prev_staff_category', models.CharField(blank=True, max_length=120, null=True)),
                ('new_staff_category', models.CharField(blank=True, max_length=120, null=True)),
                ('prev_job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('new_job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('prev_position', models.CharField(blank=True, max_length=120, null=True)),
                ('new_position', models.CharField(blank=True, max_length=120, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_disapproved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_promotions', to=settings.AUTH_USER_MODEL)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
