# Generated by Django 4.2.14 on 2024-08-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesIdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesMaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesReligion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='doa',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Appointment'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='doe',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Expiration'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='renewal',
            field=models.DateField(blank=True, null=True, verbose_name='Renewal'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_heq',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Educational Qualification'),
        ),
    ]
