# Generated by Django 4.2.14 on 2025-01-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_renewalhistorys_promotionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicesleavetype',
            name='deductible',
            field=models.BooleanField(default=False),
        ),
    ]
