# Generated by Django 4.2.13 on 2024-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_rank_alter_professionalbody_hra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesHPQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
    ]
