# Generated by Django 5.0.3 on 2024-03-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_email_address_employee_staff_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='staff_pix',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
