# Generated by Django 4.2.14 on 2024-08-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_register_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kith',
            name='kith_fname',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='kith',
            name='kith_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kith',
            name='kith_lname',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='kith',
            name='kith_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
