# Generated by Django 5.0.3 on 2024-04-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_staff_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Retired', 'Retired'), ('Suspended', 'Suspended'), ('Dismissed', 'Dismissed'), ('Interdicted', 'Interdicted'), ('Sabbatical', 'Sabbatical'), ('Inactive', 'Inactive'), ('Deceased', 'Deceased'), ('Leave of Absence', 'Leave of Absence'), ('Leave With Pay', 'Leave With Pay'), ('Leave Without Pay', 'Leave Without Pay'), ('Resigned', 'Resigned'), ('Termination', 'Resigned')], default='Active', max_length=25, verbose_name='Staff Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='staff_rank',
            field=models.CharField(blank=True, choices=[('MGT', 'Management'), ('SM', 'Senior Member'), ('SS', 'Senior Staff'), ('JS', 'Junior Staff'), ('TEMP', 'Temporary'), ('NSS', 'National Service'), ('PNS', 'Post National Service'), ('PR', 'Post Retirement Contract'), ('CS', 'Contract Staff')], max_length=50, null=True, verbose_name='Staff Rank'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Jr', 'Jr'), ('Jnr', 'Jnr'), ('Snr', 'Snr'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], max_length=20, null=True, verbose_name='Name Suffixe'),
        ),
    ]
