# Generated by Django 4.2.14 on 2025-01-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_choicesleavetype_deductible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Branch'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='directorate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Directorate'),
        ),
    ]
