# Generated by Django 5.0.3 on 2024-04-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_employee_active_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_school',
            name='certification',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('BECE', 'BECE'), ('WASSCE', 'WASSCE'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('First Degree', 'First Degree'), ('MPhil', 'MPhil'), ('MSc', 'MSc'), ('MBA', 'MBA'), ('MA', 'MA'), ('EMBA', 'EMBA'), ('PhD', 'PhD'), ('PGDip', 'PGDip')], max_length=250, null=True, verbose_name='Certification'),
        ),
        migrations.AlterField(
            model_name='staff_school',
            name='any_post',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Position Held'),
        ),
    ]
