# Generated by Django 4.2.14 on 2025-01-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_companyinformation_bank_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='cost_center',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cost Center'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='dept',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='sch_fac_dir',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='School Faculty'),
        ),
    ]
