# Generated by Django 4.2.14 on 2024-08-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_kith'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesRelationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        
    ]
