# Generated by Django 4.2.13 on 2024-06-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_choicesgender_choicesrba_choicesstafflevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesStaffStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
    ]
