# Generated by Django 4.2.14 on 2024-08-08 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_choicesrelationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kith',
            name='percentage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Beneficiary'),
        ),
       
    ]
