# Generated by Django 4.2.14 on 2025-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_companyinformation_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='acc_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Name'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='probation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Probation Period'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='pte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Point of Entry'),
        ),
    ]
