# Generated by Django 4.2.14 on 2025-02-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_companyinformation_acc_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='probation',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Probation Period'),
        ),
    ]
