# Generated by Django 4.2.14 on 2024-08-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_department_sch_fac_alter_bankbranch_bank_code'),
        ('hr', '0006_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.directorate'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='bank_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.bankbranch'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.bank'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.contract'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_center_info', to='setup.department'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_info', to='setup.department'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='sch_fac_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.school_faculty'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='staff_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.staffcategory'),
        ),
    ]
