# Generated by Django 4.2.14 on 2025-04-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_companyinformation_probation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='dept_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department Unit'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='directorate_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Directorate Unit'),
        ),
        migrations.CreateModel(
            name='StaffIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_of_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='StaffDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_of_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cost Center')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
