# Generated by Django 4.2.14 on 2024-09-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_companyinformation_directorate_kith_ben_kith_kin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_school',
            name='school_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Institution'),
        ),
    ]
