# Generated by Django 5.0.3 on 2024-04-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='record_date',
            field=models.DateField(auto_now=True),
        ),
    ]
