# Generated by Django 5.0.3 on 2024-04-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_vehicle_record_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffBank',
        ),
    ]
