# Generated by Django 4.2.14 on 2024-09-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_kith_ben_kith_kin_kith_phone_kith_residential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kith',
            name='ben',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficiary'),
        ),
        migrations.AddField(
            model_name='kith',
            name='kin',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Next of Kin'),
        ),
        migrations.AddField(
            model_name='kith',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone No.'),
        ),
        migrations.AddField(
            model_name='kith',
            name='residential',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Residential Address'),
        ),
        migrations.AddField(
            model_name='kith',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dead or Alive'),
        ),
    ]
