# Generated by Django 4.2.14 on 2025-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_companyinformation_dept_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffincome',
            name='income_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='staffincome',
            name='income_entitlement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
