# Generated by Django 5.0.3 on 2024-04-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_delete_staffbank'),
        ('setup', '0004_staffrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=20)),
                ('account_type', models.CharField(default='Current', max_length=20)),
                ('account_status', models.CharField(default='Active', max_length=20)),
                ('account_date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.bank')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.bankbranch')),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
