# Generated by Django 4.2.14 on 2024-10-05 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_department_sch_fac_alter_bankbranch_bank_code'),
        ('hr', '0009_kith_ben_kith_kin_kith_phone_kith_residential_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesLeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type of Leave')),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True, verbose_name='Academic Year')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_taken', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason for Leave')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staff_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.staffcategory')),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
