# Generated by Django 5.0.3 on 2024-04-27 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_staffbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bereavement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased', models.CharField(max_length=100, verbose_name='Deceased')),
                ('deceased_relationship', models.CharField(max_length=100, verbose_name='Relationship')),
                ('funeral_date', models.DateField()),
                ('funeral_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Funeral Time')),
                ('funeral_location', models.CharField(max_length=100, verbose_name='Location')),
                ('funeral_dress_code', models.CharField(blank=True, max_length=60, null=True, verbose_name='Dress Code')),
                ('deceased_pix', models.ImageField(blank=True, null=True, upload_to='images/funeral/')),
                ('funeral_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cel_location', models.CharField(max_length=100, verbose_name='Location')),
                ('cel_occassion', models.CharField(max_length=200, verbose_name='Occasion')),
                ('cel_date', models.DateField()),
                ('cel_dress_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dress Code')),
                ('cel_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Time')),
                ('cel_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Christening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chris_location', models.CharField(max_length=100, verbose_name='Location')),
                ('chris_date', models.DateField()),
                ('chris_dress_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dress Code')),
                ('chris_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Time')),
                ('chris_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrant', models.CharField(max_length=100, verbose_name='Celebrant')),
                ('relationship', models.CharField(blank=True, max_length=100, null=True, verbose_name='Relationship')),
                ('marriage_date', models.DateField()),
                ('marriage_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Time')),
                ('marriage_location', models.CharField(max_length=100, verbose_name='Location')),
                ('marriage_dress_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dress Code')),
                ('marriage_pix', models.ImageField(blank=True, null=True, upload_to='images/marriage/')),
                ('marriage_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_jobtitle', models.CharField(max_length=100, verbose_name='Previous Job Title')),
                ('new_jobtitle', models.CharField(max_length=100, verbose_name='New Job Title')),
                ('prev_rank', models.CharField(max_length=100, verbose_name='Previous Rank')),
                ('new_rank', models.CharField(max_length=100, verbose_name='New Rank')),
                ('effective_date', models.DateField()),
                ('approved_by', models.CharField(max_length=100, verbose_name='Approved By')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_office', models.CharField(max_length=100, verbose_name='Previous Office')),
                ('new_office', models.CharField(max_length=100, verbose_name='New Office')),
                ('prev_dept', models.CharField(max_length=100, verbose_name='Previous Department')),
                ('new_dept', models.CharField(blank=True, max_length=100, null=True, verbose_name='New Department')),
                ('effective_date', models.DateField()),
                ('approved_by', models.CharField(max_length=100, verbose_name='Approved By')),
                ('prev_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Previous Branch')),
                ('new_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='New Branch')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
