# Generated by Django 4.2.14 on 2025-05-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_choicescontribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='pf_con',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='ssn_con',
            field=models.BooleanField(default=False),
        ),
    ]
