# Generated by Django 4.2.14 on 2024-12-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_alter_bankbranch_branch_location'),
        ('hr', '0010_choicesleavetype_staff_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='AcademicYear'),
        ),
        migrations.AddField(
            model_name='medical',
            name='staff_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.staffcategory'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='complaint',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff_leave',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='AcademicYear'),
        ),
    ]
