# Generated by Django 5.0.3 on 2024-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_bereavement_celebration_christening_marriage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='staff_rank',
            field=models.CharField(blank=True, choices=[('EXEC', 'Executive'), ('MGT', 'Management'), ('SM', 'Senior Member'), ('SS', 'Senior Staff'), ('JS', 'Junior Staff'), ('CAS', 'Casual Staff'), ('NSP', 'National Service Person'), ('PNS', 'Post National Service'), ('PRC', 'Post Retirement Contract'), ('CS', 'Contract Staff')], max_length=50, null=True, verbose_name='Staff Rank'),
        ),
        migrations.AlterField(
            model_name='staff_school',
            name='finish_date',
            field=models.DateTimeField(default='2002-12-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_school',
            name='start_date',
            field=models.DateTimeField(default='2002-12-12'),
            preserve_default=False,
        ),
    ]
