# Generated by Django 4.2.14 on 2025-05-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_companyinformation_pf_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffincome',
            name='income_entitlement',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=10, null=True),
        ),
    ]
