# Generated by Django 5.0.3 on 2024-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_alter_employee_staff_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_school',
            name='finish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staff_school',
            name='start_date',
            field=models.DateField(),
        ),
    ]
