# Generated by Django 4.2.14 on 2024-12-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_remove_medical_quota_balance_medical_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='hospital_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hospital'),
        ),
    ]
