# Generated by Django 4.2.14 on 2025-05-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_alter_staffincome_income_entitlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='basic_entitled_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5, null=True),
        ),
    ]
