# Generated by Django 4.2.14 on 2025-01-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_alter_medical_hospital_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='contract',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contract'),
        ),
    ]
