# Generated by Django 4.2.14 on 2025-05-28 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_alter_companyinformation_basic_entitled_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesExitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exit Type')),
                ('exit_date', models.DateField()),
                ('exit_reason', models.TextField(blank=True, null=True, verbose_name='Reason for Exit')),
                ('exit_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_disapproved', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exits', to=settings.AUTH_USER_MODEL)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
