# Generated by Django 5.0.3 on 2024-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_alter_staff_school_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kith',
            name='kith_relationship',
            field=models.CharField(choices=[('Wife', 'Wife'), ('Husband', 'Husband'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother'), ('Self', 'Self')]),
        ),
        migrations.AlterField(
            model_name='medical',
            name='relationship',
            field=models.CharField(choices=[('Wife', 'Wife'), ('Husband', 'Husband'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother'), ('Self', 'Self')]),
        ),
    ]
