# Generated by Django 4.2.14 on 2025-01-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_alter_companyinformation_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='staff_cat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Category'),
        ),
    ]
