# Generated by Django 4.2.14 on 2025-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_choicesexittype_exits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Active Phone No.'),
        ),
    ]
