# Generated by Django 4.2.14 on 2025-01-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_alter_staff_leave_staff_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='staff_cat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Category'),
        ),
    ]
