# Generated by Django 4.2.14 on 2025-06-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
