# Generated by Django 4.2.14 on 2025-01-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_alter_medical_staff_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='oname',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Other Names'),
        ),
    ]
