# Generated by Django 4.2.14 on 2025-01-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_employee_oname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesMedicalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
