# Generated by Django 4.2.14 on 2025-07-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_permissiontag_usertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='staff_pix',
            field=models.URLField(blank=True, null=True),
        ),
    ]
