# Generated by Django 4.2.14 on 2025-01-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_medical_nature_medical_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesMedicalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
