# Generated by Django 4.2.14 on 2025-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_staffdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kith',
            name='kith_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
