# Generated by Django 4.2.14 on 2025-08-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_alter_kith_kith_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdeduction',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='staffdeduction',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='staffincome',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='staffincome',
            name='start_month',
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='is_one_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffincome',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffincome',
            name='is_one_time',
            field=models.BooleanField(default=False),
        ),
    ]
