# Generated by Django 4.2.14 on 2025-08-12 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_payroll_net_taxable_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='acc_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='accno',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='active_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Staff Status'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Branch'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='basic_entitled_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='campus',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='contract',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='cost_center',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cost Center'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='dept',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='dept_unit',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Department Unit'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='directorate',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Directorate'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='directorate_unit',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Directorate Unit'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Official Email'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='job_description',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='pte',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Point of Entry'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Designation/Rank'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='sch_fac_dir',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='School Faculty'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='staff_cat',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Staff Category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='active_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Active Phone No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='car',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Car Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='chassis',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Chassis Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='completion_year',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Year of Completion'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='denomination',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Denomination'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='digital',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Digital Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=50, verbose_name='Persoanl Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ethnic',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ethnic Group'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gcardno',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ID Card No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='heq',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Highest Academic Qualification'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_town',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Home Town'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hpq',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Highest Professional Qualification'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='idtype',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ID Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Institution of Study'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='m_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middlenames',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Middle Names'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='oname',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Other Names'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_heq',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Other Educational Qualification'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pob',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='postal',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Postal Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residential',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Residential Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssnitno',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='SSNIT No.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='staff_pix',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='study_area',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Area of Study'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Name Suffixe'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vech_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Vechicle Type'),
        ),
        migrations.AlterField(
            model_name='kith',
            name='ben',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Beneficiary'),
        ),
        migrations.AlterField(
            model_name='kith',
            name='kin',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Next of Kin'),
        ),
        migrations.AlterField(
            model_name='kith',
            name='kith_fname',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='kith',
            name='kith_gender',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='kith',
            name='kith_lname',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='kith',
            name='kith_middlenames',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Middle Names'),
        ),
        migrations.AlterField(
            model_name='kith',
            name='kith_relationship',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='kith',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='kith',
            name='residential',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Residential Address'),
        ),
        migrations.AlterField(
            model_name='kith',
            name='status',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Dead or Alive'),
        ),
        migrations.CreateModel(
            name='PendingEmployeeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20, verbose_name='Title')),
                ('lname', models.CharField(max_length=120, verbose_name='Surname')),
                ('fname', models.CharField(max_length=120, verbose_name='First Name')),
                ('middlenames', models.CharField(blank=True, default='', max_length=120, verbose_name='Middle Names')),
                ('oname', models.CharField(blank=True, default='', max_length=120, verbose_name='Other Names')),
                ('suffix', models.CharField(blank=True, default='', max_length=20, verbose_name='Name Suffixe')),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('m_status', models.CharField(blank=True, default='', max_length=50, verbose_name='Marital Status')),
                ('nationality', models.CharField(blank=True, default='', max_length=50, verbose_name='Nationality')),
                ('ethnic', models.CharField(blank=True, default='', max_length=50, verbose_name='Ethnic Group')),
                ('home_town', models.CharField(blank=True, default='', max_length=100, verbose_name='Home Town')),
                ('region', models.CharField(blank=True, default='', max_length=50, verbose_name='Region')),
                ('pob', models.CharField(blank=True, default='', max_length=50, verbose_name='Place of Birth')),
                ('religion', models.CharField(blank=True, default='', max_length=50, verbose_name='Religion')),
                ('denomination', models.CharField(blank=True, default='', max_length=50, verbose_name='Denomination')),
                ('email_address', models.EmailField(blank=True, default='', max_length=50, verbose_name='Persoanl Email')),
                ('active_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Active Phone No.')),
                ('ssnitno', models.CharField(blank=True, default='', max_length=50, verbose_name='SSNIT No.')),
                ('idtype', models.CharField(blank=True, default='', max_length=50, verbose_name='ID Type')),
                ('gcardno', models.CharField(blank=True, default='', max_length=50, verbose_name='ID Card No.')),
                ('digital', models.CharField(blank=True, default='', max_length=100, verbose_name='Digital Address')),
                ('residential', models.CharField(blank=True, default='', max_length=100, verbose_name='Residential Address')),
                ('postal', models.CharField(blank=True, default='', max_length=100, verbose_name='Postal Address')),
                ('blood', models.CharField(blank=True, default='', max_length=50, verbose_name='Blood Group')),
                ('car', models.CharField(blank=True, default='', max_length=50, verbose_name='Car Number')),
                ('chassis', models.CharField(blank=True, default='', max_length=50, verbose_name='Chassis Number')),
                ('vech_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Vechicle Type')),
                ('study_area', models.CharField(blank=True, default='', max_length=50, verbose_name='Area of Study')),
                ('heq', models.CharField(blank=True, default='', max_length=100, verbose_name='Highest Academic Qualification')),
                ('completion_year', models.CharField(blank=True, default='', max_length=100, verbose_name='Year of Completion')),
                ('institution', models.CharField(blank=True, default='', max_length=100, verbose_name='Institution of Study')),
                ('other_heq', models.CharField(blank=True, default='', max_length=100, verbose_name='Other Educational Qualification')),
                ('hpq', models.CharField(blank=True, default='', max_length=100, verbose_name='Highest Professional Qualification')),
                ('staff_pix', models.URLField(blank=True, default='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_staff', to=settings.AUTH_USER_MODEL)),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_updates', to='hr.employee')),
            ],
        ),
    ]
