# Generated by Django 4.2.14 on 2025-08-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_payroll_net_taxable_pay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmployeeUpdate',
            fields=[
                ('staffno', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Staff Number')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('lname', models.CharField(max_length=120, verbose_name='Surname')),
                ('fname', models.CharField(max_length=120, verbose_name='First Name')),
                ('middlenames', models.CharField(blank=True, max_length=120, null=True, verbose_name='Middle Names')),
                ('oname', models.CharField(blank=True, max_length=120, null=True, verbose_name='Other Names')),
                ('suffix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Name Suffixe')),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('m_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marital Status')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationality')),
                ('ethnic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ethnic Group')),
                ('home_town', models.CharField(blank=True, max_length=100, null=True, verbose_name='Home Town')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Region')),
                ('pob', models.CharField(blank=True, max_length=50, null=True, verbose_name='Place of Birth')),
                ('religion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Religion')),
                ('denomination', models.CharField(blank=True, max_length=50, null=True, verbose_name='Denomination')),
                ('email_address', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Persoanl Email')),
                ('active_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Active Phone No.')),
                ('ssnitno', models.CharField(blank=True, max_length=50, null=True, verbose_name='SSNIT No.')),
                ('idtype', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Type')),
                ('gcardno', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Card No.')),
                ('digital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Digital Address')),
                ('residential', models.CharField(blank=True, max_length=100, null=True, verbose_name='Residential Address')),
                ('postal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Postal Address')),
                ('blood', models.CharField(blank=True, max_length=50, null=True, verbose_name='Blood Group')),
                ('car', models.CharField(blank=True, max_length=50, null=True, verbose_name='Car Number')),
                ('chassis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chassis Number')),
                ('vech_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vechicle Type')),
                ('study_area', models.CharField(blank=True, max_length=50, null=True, verbose_name='Area of Study')),
                ('heq', models.CharField(blank=True, max_length=100, null=True, verbose_name='Highest Academic Qualification')),
                ('completion_year', models.CharField(blank=True, max_length=100, null=True, verbose_name='Year of Completion')),
                ('institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Institution of Study')),
                ('other_heq', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Educational Qualification')),
                ('hpq', models.CharField(blank=True, max_length=100, null=True, verbose_name='Highest Professional Qualification')),
                ('staff_pix', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
