# Generated by Django 4.2.14 on 2025-08-11 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_pendingemployeeupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingemployeeupdate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingemployeeupdate',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
