# Generated by Django 4.2.14 on 2025-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_alter_companyinformation_acc_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Branch'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
    ]
