# Generated by Django 4.2.14 on 2025-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_alter_companyinformation_bank_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='cost_center',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cost Center'),
        ),
    ]
