# Generated by Django 4.2.14 on 2025-08-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_alter_companyinformation_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='dept',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='dept_unit',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Department Unit'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='directorate',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Directorate'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='directorate_unit',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Directorate Unit'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='sch_fac_dir',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='School Faculty'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='staff_cat',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Staff Category'),
        ),
    ]
