# Generated by Django 4.2.14 on 2025-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_alter_companyinformation_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kith',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
