# Generated by Django 4.2.14 on 2025-08-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_alter_kith_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tin',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='SSNIT No.'),
        ),
        migrations.AddField(
            model_name='pendingemployeeupdate',
            name='tin',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='SSNIT No.'),
        ),
    ]
