# Generated by Django 4.2.14 on 2025-10-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_employee_tin_pendingemployeeupdate_tin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='ssf',
            new_name='ssf_employee',
        ),
        migrations.AddField(
            model_name='payroll',
            name='ssf_employer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
