# Generated by Django 4.2.14 on 2025-10-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0032_rename_ssf_payroll_ssf_employee_payroll_ssf_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRelief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reliefs', to='hr.payroll')),
            ],
            options={
                'db_table': 'payroll_relief',
                'unique_together': {('payroll', 'relief_type')},
            },
        ),
        migrations.CreateModel(
            name='PayrollIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_of_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='hr.payroll')),
            ],
            options={
                'db_table': 'payroll_income',
                'unique_together': {('payroll', 'income_type')},
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='hr.payroll')),
            ],
            options={
                'db_table': 'payroll_deduction',
                'unique_together': {('payroll', 'deduction_type')},
            },
        ),
        migrations.CreateModel(
            name='PayrollBenefitInKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits_in_kind', to='hr.payroll')),
            ],
            options={
                'db_table': 'payroll_benefit_in_kind',
                'unique_together': {('payroll', 'benefit_type')},
            },
        ),
    ]
