# Generated by Django 4.2.14 on 2025-10-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_payrollrelief_payrollincome_payrolldeduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('installments', models.IntegerField(default=1)),
                ('monthly_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('academic_year', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('start_deduction_date', models.DateField(blank=True, null=True)),
                ('end_deduction_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('medical_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.medical')),
                ('staffno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalSurchargePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('surcharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hr.medicalsurcharge')),
            ],
        ),
    ]
