# Generated by Django 4.2.14 on 2025-11-04 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_journalline_date'),
        ('hr', '0034_medicalsurcharge_medicalsurchargepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='is_journalized',
            field=models.BooleanField(default=False, help_text='Whether this payroll has been posted to journal'),
        ),
        migrations.CreateModel(
            name='PayrollJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the payroll month')),
                ('reference', models.CharField(help_text='e.g., PAYROLL-JAN-2025', max_length=100, unique=True)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('staff_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_posted', models.BooleanField(default=False, help_text='Whether the journal has been posted to ledger')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_journals', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_journals', to='ledger.journal')),
            ],
            options={
                'db_table': 'payroll_journal',
                'ordering': ['-month'],
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='payroll_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='hr.payrolljournal'),
        ),
        migrations.CreateModel(
            name='PayrollAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('basic_salary', 'Basic Salary'), ('allowance', 'Allowance'), ('ssf_employee', 'SSF Employee Contribution'), ('ssf_employer', 'SSF Employer Contribution'), ('pf_employee', 'PF Employee Contribution'), ('pf_employer', 'PF Employer Contribution'), ('paye', 'PAYE (Income Tax)'), ('other_deduction', 'Other Deductions'), ('net_salary', 'Net Salary Payable')], max_length=50)),
                ('sub_type', models.CharField(blank=True, help_text="For allowances or deductions (e.g., 'Housing Allowance')", max_length=100, null=True)),
                ('description_template', models.CharField(help_text='Template for journal line description (use {month} and {year} placeholders)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_credit_mappings', to='ledger.account')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_debit_mappings', to='ledger.account')),
            ],
            options={
                'db_table': 'payroll_account_mapping',
                'ordering': ['account_type', 'sub_type'],
                'unique_together': {('account_type', 'sub_type')},
            },
        ),
    ]
