# Generated by Django 4.2.13 on 2024-06-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_long_name', models.CharField(max_length=250, verbose_name='Name of Bank')),
                ('bank_short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Short Name')),
                ('bank_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_long_name', models.CharField(max_length=250, verbose_name='Name of Department')),
                ('dept_short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('dept_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=250, verbose_name='Name of Hospital')),
                ('hospital_location', models.CharField(max_length=250, verbose_name='Location of Hospital')),
                ('hospital_contact_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of Contact')),
                ('hospital_contact_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Contact Phone')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150, verbose_name='Job Title')),
                ('job_rank', models.CharField(blank=True, choices=[('None', 'None')], max_length=150, null=True, verbose_name='Job Title Rank')),
                ('salary_level', models.CharField(blank=True, max_length=150, null=True, verbose_name='Salary Level')),
                ('jobtitle_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assoc_long_name', models.CharField(max_length=250, verbose_name='Name of Association')),
                ('assoc_short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('assoc_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=150, verbose_name='Name of School')),
                ('school_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('school_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Location')),
                ('school_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('school_type', models.CharField(choices=[('BS', 'Basic School'), ('SS', 'Secondary School'), ('TC', 'Post Secondary School'), ('UN', 'University')], default='SS', max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_rank', models.CharField(max_length=150, verbose_name='Staff Rank')),
                ('staff_level', models.CharField(choices=[('None', 'None')], max_length=50, verbose_name='Staff Level')),
                ('rank_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=250, verbose_name='Name of Branch')),
                ('branch_location', models.CharField(max_length=250, verbose_name='Branch Location')),
                ('bank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.bank')),
            ],
        ),
    ]
