# Generated by Django 5.0.3 on 2024-03-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_long_name', models.CharField(max_length=250, verbose_name='Name of Bank')),
                ('bank_short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Short Name')),
                ('bank_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_long_name', models.CharField(max_length=250, verbose_name='Name of Department')),
                ('dept_short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('dept_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=250, verbose_name='Name of Hospital')),
                ('hospital_location', models.CharField(max_length=250, verbose_name='Location of Hospital')),
                ('hospital_contact_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of Contact')),
                ('hospital_contact_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Contact Phone')),
            ],
        ),
        migrations.CreateModel(
            name='ProfBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assoc_long_name', models.CharField(max_length=250, verbose_name='Name of Association')),
                ('assoc_short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('assoc_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=150, verbose_name='Name of School')),
                ('school_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('school_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Location')),
                ('school_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=250, verbose_name='Name of Branch')),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Branch Code')),
                ('bank_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('branch_location', models.CharField(max_length=250, verbose_name='Branch Location')),
                ('bank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.bank')),
            ],
        ),
    ]
