# Generated by Django 5.0.3 on 2024-03-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('PR', 'Primary'), ('SS', 'Secondary'), ('T1', 'Post Secondary'), ('T2', 'University')], default='SS'),
        ),
    ]
