# Generated by Django 4.2.14 on 2024-07-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=250, verbose_name='Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=250, verbose_name='Contract Type')),
            ],
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_name', models.CharField(max_length=250, verbose_name='Directorate')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qual_name', models.CharField(max_length=250, verbose_name='Qualification Title')),
                ('qual_abbr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='School_Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_fac_name', models.CharField(max_length=250, verbose_name='School/Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, verbose_name='Staff Category')),
                ('category_abbr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abbreviation')),
            ],
        ),
    ]
