# Generated by Django 4.2.14 on 2024-08-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_new_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='job_rank',
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='staff_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.staffcategory'),
        ),
    ]
