# Generated by Django 5.0.3 on 2024-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_school_school_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankbranch',
            name='bank_notes',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='branch_code',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('BS', 'Basic School'), ('SS', 'Secondary School'), ('TC', 'Post Secondary School'), ('UN', 'University')], default='BS'),
        ),
    ]
