# Generated by Django 5.0.3 on 2024-03-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_remove_bankbranch_bank_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_rank', models.CharField(max_length=150, verbose_name='Staff Rank')),
                ('staff_level', models.CharField(choices=[('MGT', 'Management'), ('SM', 'Senior Member'), ('SS', 'Senior Staff'), ('JS', 'Junior Staff'), ('CAS', 'Casual Staff')], max_length=50, verbose_name='Staff Level')),
                ('rank_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
    ]
