# Generated by Django 4.2.14 on 2024-08-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_remove_jobtitle_job_rank_jobtitle_staff_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sch_fac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.school_faculty'),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='bank_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.bank'),
        ),
    ]
