# Generated by Django 4.2.14 on 2025-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_salaryscale_unit_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometype',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='incometype',
            name='taxable',
            field=models.BooleanField(default=False),
        ),
    ]
