# Generated by Django 5.0.3 on 2024-04-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_staffrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150, verbose_name='Job Title')),
                ('job_rank', models.CharField(blank=True, max_length=150, null=True, verbose_name='Job Title Rank')),
                ('salary_level', models.CharField(blank=True, max_length=150, null=True, verbose_name='Salary Level')),
                ('jobtitle_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
