# Generated by Django 4.2.14 on 2024-12-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_department_sch_fac_alter_bankbranch_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='branch_location',
            field=models.TextField(max_length=300, verbose_name='Branch Location'),
        ),
    ]
