# Generated by Django 4.2.14 on 2025-05-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_incometype_tax_rate_incometype_taxable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('employer_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
