# Generated by Django 4.2.14 on 2025-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_contributionrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=3, help_text='e.g. 17.5% = 0.175', max_digits=4)),
            ],
            options={
                'ordering': ['lower_limit'],
            },
        ),
    ]
