# Generated by Django 5.0.3 on 2024-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='job_rank',
            field=models.CharField(blank=True, choices=[('EXEC', 'Executive'), ('MGT', 'Management'), ('SM', 'Senior Member'), ('SS', 'Senior Staff'), ('JS', 'Junior Staff'), ('CAS', 'Casual Staff'), ('NSP', 'National Service Person'), ('PNS', 'Post National Service'), ('PRC', 'Post Retirement Contract'), ('CS', 'Contract Staff')], max_length=150, null=True, verbose_name='Job Title Rank'),
        ),
        migrations.AlterField(
            model_name='staffrank',
            name='staff_level',
            field=models.CharField(choices=[('EXEC', 'Executive'), ('MGT', 'Management'), ('SM', 'Senior Member'), ('SS', 'Senior Staff'), ('JS', 'Junior Staff'), ('CAS', 'Casual Staff'), ('NSP', 'National Service Person'), ('PNS', 'Post National Service'), ('PRC', 'Post Retirement Contract'), ('CS', 'Contract Staff')], max_length=50, verbose_name='Staff Level'),
        ),
    ]
