# Generated by Django 4.2.14 on 2025-01-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_alter_bankbranch_branch_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='staff_cat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Category'),
        ),
    ]
