# Generated by Django 4.2.14 on 2025-05-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_taxband'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxband',
            options={},
        ),
        migrations.AlterField(
            model_name='taxband',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='e.g. 17.5% = 0.175', max_digits=5),
        ),
    ]
