# Generated by Django 4.2.14 on 2025-05-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_alter_taxband_options_alter_taxband_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionrate',
            name='employee_rate',
        ),
        migrations.RemoveField(
            model_name='contributionrate',
            name='employer_rate',
        ),
        migrations.RemoveField(
            model_name='contributionrate',
            name='name',
        ),
        migrations.AddField(
            model_name='contributionrate',
            name='employee_pf_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contributionrate',
            name='employee_ssnit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contributionrate',
            name='employer_pf_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contributionrate',
            name='employer_ssnit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
