# Generated by Django 4.2.14 on 2025-05-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_remove_contributionrate_employee_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbranch',
            name='sort_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sort Code'),
        ),
    ]
