# Generated by Django 4.2.14 on 2025-06-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_bankbranch_sort_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometype',
            name='bik_cap',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='incometype',
            name='bik_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
