# Generated by Django 4.2.14 on 2025-06-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_incometype_bik_cap_incometype_bik_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='export_format',
            field=models.JSONField(blank=True, null=True, verbose_name='Export Format'),
        ),
    ]
