# Generated by Django 4.2.14 on 2025-06-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_bank_export_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank_long_name',
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_short_name',
            field=models.CharField(default='Bank', max_length=250, verbose_name='Bank Short Name'),
        ),
    ]
