# Generated by Django 4.2.14 on 2025-06-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_remove_bank_bank_long_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_short_name',
            field=models.CharField(max_length=250, verbose_name='Bank Short Name'),
        ),
    ]
