# Generated by Django 4.2.14 on 2025-07-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_alter_bank_bank_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
