# Generated by Django 4.2.14 on 2025-08-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_academicyear_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionrate',
            name='withholding_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
