# Generated by Django 4.2.14 on 2025-08-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_contributionrate_withholding_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometype',
            name='withholding_tax',
            field=models.BooleanField(default=False),
        ),
    ]
