# Generated by Django 4.2.14 on 2025-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_incometype_withholding_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
